Import('*')

env = Environment(CPPFLAGS="-g ",
					CPPPATH='#renderer')

# non-portable hack to force the use of the static version =(
# I'm starting to dislike scons now
# check http://old.nabble.com/How-to-force-the-use-of-a-static-library-when-the-dynamic-library-is-available-as-well-td20476343.html
static_jpeg_lib = env.File('/usr/lib/libjpeg.a')

env.Program('rendertrial', Glob('*.cpp'),
		LIBS = ['libSDL', 'pthread', 'dl', 'GL', 'GLU', renderer, "jpeg"])
